# Site settings
title: Adventures in Web Development and Beyond 
email: sas1ni69@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hassanin-ahmed.com" # the base hostname & protocol for your site
twitter_username: sas1ni69
github_username: sas1ni69

# Build settings
markdown: kramdown
